- entry_point.sh
The license was add before the shebang, which doesn't allow docker to run the script as an entry-point. I also update the shebang to a more supported "#!/usr/bin/env bash" version.
Change-Id: Ibe925462dbfbf35bc468855a8361475ddfff50bb
Signed-off-by: Louis Mayencourt <louis.mayencourt@arm.com>
> Fix docker entrypoint shebang and license position

- sysroot/Dockerfile_ubuntu_arm64_prebuilt
Add the Dockerfile used on the instructions on how to cross-compile
one or more packages against a pre-built ROS2 stack.
related to https://github.com/ros2/ros2_documentation/pull/29
Change-Id: I092f6706f0a91741e895ea1e9756a975e42d787d
Signed-off-by: Louis Mayencourt <louis.mayencourt@arm.com>
> Add sysroot Dockerfile examples for pre-built instructions

- entry_point.sh
- sysroot/Dockerfile_ubuntu_arm64
- sysroot/Dockerfile_ubuntu_armhf
The class-loader package fails if the pre-built binary of Poco
library is used. The PocoFoundationTargets.cmake file coming
with the pre-built binary have hardcoded paths to libz and libpcre
which makes the cross-compilation to fail.
This fix removes Poco library from the apt-get list and forces
to build it inside the poco_vendor ros2 packages.
related to: https://github.com/ros2/ros2_documentation/pull/29
> Fix for class-loader libz and pcre link issue

- entry_point.sh
Remove the docker container after exporting to allow consecutive calls
of the entry-point script.
> Clean docker container after extracting it

- entry_point.sh
- sysroot/Dockerfile_ubuntu_arm64
- sysroot/Dockerfile_ubuntu_armhf
Improve the exported filesystem by:
- resolving the broken symlink by changing them to relative one with the "symlinks" tools 
- export /etc
This allow us to build more ROS2 packages
> Improve target file system export

- Dockerfile_cc_for_arm
Use an argument to select which version of ROS2 to fetch. This can be specified with the `--build-arg` argument on the docker build command:
docker build --build-arg ROS2_VERSION=release-crystal ...
> Add docker argument to specify the ros2 version

- Dockerfile_cc_for_arm
- entry_point.sh
- sysroot/Dockerfile_ubuntu_arm
- sysroot/Dockerfile_ubuntu_arm64_prebuilt
* ros-visualization package are ignored
* the new libopensplice69 is not installed as dependency
related to: https://github.com/ros2/ros2_documentation/pull/29
> Update for latest release (Crystal Clemmys)

- cmake-toolchains/generic_linux.cmake
Set the moc executable to the host binary instead of using the one found on the target file system when cross-compiling.
>  Define host Qt moc executable

- cross_compile/sysroot_compiler.py
- test/test_sysroot_compiler.py
USER env var doesn't port to all build environments (e.g. DOCKER) and doesn't necessarily work on Windows. `getpass` module provides the portable tool
See http://build.ros2.org/job/Ddev__cross_compile__ubuntu_bionic_amd64/1/testReport/junit/cross_compile.test/test_sysroot_compiler/test_get_workspace_image_tag/
> Remove non-portable use of USER environment variable

- CONTRIBUTING.md
- mixins/lint.py
- test/dummy_pkg/main.cpp
- test/test_copyright.py
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>
`CONTRIBUTOR.md` is the default file we've been using until now. I'd rather keep the files similar until we decide on a different one.
> Add test_copyright.py and fix copyright issues

- cross_compile/Dockerfile_workspace
I was trying to cross compile ROS2 to armhf architecture and discovered that link to `mixins/index.yaml` is broken. This PR fix it, but shouldn't sysroot_compiler use local file instead?
---
Outside of this, there is no remark in README that `Dockerfile_workspace` should be putted into `sysroot` folder. If this is correct, I guess it should be stated here: https://github.com/ros-tooling/cross_compile#3-run-the-cross-compilation-script . At least I couldn't get it to work until I put it there.
Connected to this - maybe it should be stated explicitely that argument `--sysroot-path` must be absolute path; that took some time to realise why `sysroot/Dockerfile_workspace` was not found.
> Fix: Wrong link to `mixins/index.yaml` in Dockerfile_workspace

- cross_compile/Dockerfile_workspace
Same changes as #40 moved to local branch due to status checks failing.
Signed-off-by: Anas Abou Allaban <allabana@amazon.com>
> Move symlinks install and convert apt to apt-get

- README.md
Changed the instructions for installing from source to use `master` for repos instead of `dashing` since the instructions are passing `--rosdistro=eloquent` for `rosdep install`
> Use master instead of dashing if rosdistro is eloquent

- cross_compile/sysroot_compiler.py
Replace variable typing hints with typing hint comments to support Python 3.5
> Convert typing hints on variables to comments

- .github/workflows/test.yml
0.0.5 fixes a bug where PR from external forks were not build properly.
> Update CI script

- cross_compile/sysroot_compiler.py
As far as I understand, this small change is enough to make sysroot_compiler work with relative `--sysroot-path`.
> Allow to use relative `--sysroot-path`

- README.md
* Simplified `Prerequisites` steps
* Remove unnecessary apt installs
* Use `apt` instead of `apt-get`
* Simplified `Installing from source` steps
* Use ros2run from cross_compile workspace
* Add a comment that the required ros2cli tooling can be sourced elsewhere on the host.
* Simplified `usage` steps
* build the required structure as a single step
* use `curl` instead of `wget` since `curl` is used earlier in the document.
> Update README documentation so installation reflects current state of project.

- cross_compile/sysroot_compiler.py
When encountered [this](https://github.com/ros-tooling/cross_compile/issues/62) I found after interrupt during `export_workspace_sysroot_image()` that there is no my former `sysroot`, which was very confusing.
IMO, the best way is to extract resulting tree into _another_ folder than origin one in order to preserve original files, but following current script I propose to move `rm` command closer to tree extraction.
> Moved rmtree(target_sysroot) closer to sysroot_tar.extractall()

- .github/workflows/test.yml
This uploads the new releases of this package to the test PyPI
repository. We will switch the main PyPI repo, once we validate this
workflow works properly.
> Automatically upload new releases to PyPI

- cross_compile/Dockerfile_workspace
* Make sure to clean up apt caches in dockerfile wherever they are used
* move workspace source copying to as late as possible to maximize Docker cache use
* Remove unecessary logic around manually creating rosdistro directories, apt install takes care of it
> Dockerfile cleanup

- cross_compile/ros2_cross_compile.py
Make the documentation for the sysroot argument correct by defaulting to the current working directory. 
Before this PR, if you didn't pass the argument, an error would be raised by the SysrootCompiler verifying its argument.
> Make the documentation for the sysroot argument correct 

- cross_compile/sysroot_compiler.py
- test/test_sysroot_compiler.py
These two setup files are not used by current functionality, and give error messages every run. Removing.
> Remove logic around setup scripts which are not being used

- cross_compile/Dockerfile_ros2
Enable `en_US.UTF-8` for `locale-gen` before running `locale-gen`
> Enable en_US.UTF-8 locale in locale-gen

- cross_compile/Dockerfile_ros2
The line adding the ROS apt sources explicitly specified architectures. Since we are working in an emulated environment, the only architecture we need is the "native"/emulated one, so we don't have to specify. 
This fixes the use case for armhf builds that have ROS rosdeps, because the armhf sources were not being added.
> Allow for finding ROS packages in armhf builds

- cross_compile/ros2_cross_compile.py
- cross_compile/sysroot_compiler.py
- test/test_sysroot_compiler.py
Be explicit about required arguments passed to constructors and their types.
> Don't pass argparse.Namespace out of the argument parsing context 

- cross_compile/Dockerfile_ros2
- cross_compile/sysroot_compiler.py
- test/run_e2e_test.sh
The install dir was not being output to the correct place. The desired location was next to the sources, like in a regular colcon workspace.
Add an architecture-specific suffix to the export install directory so that multiple cross-compiles can be done.
Add these checks to the e2e test to make sure this keeps working.
> Export the cross compiled install dir to the correct location

- README.md
- cross_compile/Dockerfile_ros
- cross_compile/ros2_cross_compile.py
- cross_compile/sysroot_compiler.py
- setup.py
- test/run_e2e_test.sh
- test/test_sysroot_compiler.py
* Rename `Dockerfile_ros2` to `Dockerfile_ros`
* Rename CLI argument `--distro` to `--rosdistro`
* Reword documentation and variables from `ros2` to `ros`
* Add ROS build support in emulated build
* Add logic to use correct base docker images for supported ROS distros
> Add ROS support

- cross_compile/sysroot_compiler.py
- mixins/cross-compile.mixin
`rosbag2` failed to compile on 32-bit platforms because it depended on `lsan` library that was not available in 32-bit. This was fixed as part of https://github.com/ros2/rosbag2/issues/142 so `rosbag2` no longer needs to be skipped in armhf colcon mixin.
> Don't skip packages in armhf mixins

- .vale.ini
Add `.vale.ini` for the Vale GH action.
Signed-off-by: Anas Abou Allaban <allabana@amazon.com>
> Add vale config

- .github/workflows/e2e_test.yml
Run the e2e test for supported platform, os and rosdistros (except Kinetic) through a nightly GH actions workflow.
Successful run [here](https://github.com/prajakta-gokhale/cross_compile/commit/1456ab68509f4746dcfa8d78d9219ffe8ef35881/checks?check_suite_id=365943265).
> Add GH Action workflow for e2e test

- cross_compile/sysroot_compiler.py
- test/run_e2e_test.sh
Since ROS does not have the concept of DDS/RMW, remove it from the docker image name produced by the script.
> Remove RMW string from docker image name

- .github/workflows/e2e_test.yml
- cross_compile/Dockerfile_ros
Changes had to be made to the dockerfile for it to work correctly with Debian Buster and find correct sources lists from rosdep.
> Add armhf platform to e2e tests

- .gitignore
- cross_compile/sysroot_compiler.py
- setup.py
- test/test_sysroot_compiler.py
This issue was revealed by an unrelated network issue in https://github.com/ros-tooling/cross_compile/pull/105/checks?check_run_id=378401015 that caused the docker build to fail.
Fix the issue and add relevant regression tests.
> Fix and add unit test for incorrect BuildError constructor

- .gitignore
- README.md
- cross_compile/Dockerfile_ros
- cross_compile/ros2_cross_compile.py
- cross_compile/sysroot_compiler.py
- test/custom-setup-with-data.sh
- test/custom-setup.sh
- test/data/arbitrary.txt
- test/run_unit_tests.sh
- test/test_sysroot_compiler.py
Provide a new commandline option (and corresponding documentation) for a user to have arbitrary custom data included in the sysroot creation process. This data is available to the custom script that the user can provide.
Fixes #103
> Allow user to provide custom data directory

- cross_compile/ros2_cross_compile.py
- test/test_entrypoint.py
Increases code coverage and lets us know that the syntax and imports in the entrypoint are ok.
> Add trivial test to call the argparser

- .github/workflows/test.yml
Tested this on a prior version this with the check changed to run on pull_request. After a full successful check suite, reverted back to only running on push.
> Fix PyPI action on push to master

- .github/workflows/pip_e2e_test.yml
- .github/workflows/prod_test.yml
This PR adds 2 new workflows for E2E testing an install from PyPi and TestPyPi.
This PR **should not be merged** until this package is released to both PyPi and TestPyPi.
Signed-off-by: Anas Abou Allaban <allabana@amazon.com>
> Nightly PyPi release test

- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_compiler.py
- test/test_sysroot_compiler.py
This feature has no clear use case and is not tested, so it shouldn't be here.
> Remove docker network config option

- ros_cross_compile/builders.py
- ros_cross_compile/docker_client.py
- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_creator.py
- test/test_builders.py
- test/test_docker_client.py
- test/test_sysroot_creator.py
Progress toward #106 
Part of replacement for #139
Factors out docker operations into a wrapper DockerClient class that encapsulates our common usage patterns. Will be used for upcoming build stages as well.
> Factor out docker operations into a wrapper client class

- README.md
- ros_cross_compile/docker/build_workspace.sh
- test/dummy_pkg_ros2/CMakeLists.txt
- test/dummy_pkg_ros2/main.cpp
- test/dummy_pkg_ros2/package.xml
- test/run_e2e_test.sh
The `build_workspace.sh` script caused an error upon sourcing `setup.bash` because of unset variables, if ROS was actually installed.
To fix:
* remove the `set -u` option for that script
* add explicit checking for required variables
* update e2e test dummy package to require ROS2
After updating the package but before updating the script, the e2e test failed. Now it succeeds and is performing a more thorough test.
Part of the replacement for #139 
> Fix workspace builder script when ROS actually installed,

- ros_cross_compile/docker/sysroot.Dockerfile
We installed these at some point in the past out of either copy-paste, or a need that no longer exists.
* `git` - user handles workspace sources on their own
* `wget` - we are not using it, we did at one point to pull `ros2.repos`
* `argcomplete` - there's no interactive portion to this container, there's no need for it
* `vcstool` - user handles workspace sources on their own
> Remove dependencies installed in the sysroot that are not used by anything

- ros_cross_compile/docker/sysroot.Dockerfile
We were seeing some flakiness in the end-to-end tests, failing to install package `humanity-icon-theme` occasionally. This was being pulled in as a "recommended" apt package below `colcon-common-extensions`, but is not needed.
See example failure https://github.com/ros-tooling/cross_compile/pull/155/checks?check_run_id=466189777
This has the added benefit of shaving some time ~1-3mins off each e2e run, and ~150MB off of the default e2e test container. 
> Use no-install-recommends for all apt install commands

- ros_cross_compile/docker_client.py
- test/test_docker_client.py
Before this change, if a command run in a container failed, it would print the error but keep running onto the next step. This makes the command fail by not detaching the container.
It also introduces the `command` parameter for easier testing and extensibility.
> Raise exception when `docker run` fails

- tox.ini
For example i am iterating on one test, this allows me to do the following to regex match pytests for "depend"
```
tox -e py -- -k depend
```
> Expose posargs in tox config so that developer can send pytest arguments

- README.md
- ros_cross_compile/dependencies.py
- ros_cross_compile/docker/gather_rosdeps.sh
- ros_cross_compile/docker/rosdep.Dockerfile
- ros_cross_compile/docker/sysroot.Dockerfile
- ros_cross_compile/docker_client.py
- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_creator.py
- test/test_dependencies.py
Fixes https://github.com/ros-tooling/cross_compile/issues/106
Creates a separate container, that runs natively, and outputs a script for installing workspace dependencies.
If the script has not changed (no dependencies have changed), the docker cache is used and the build can begin immediately. This makes the tool much more usable by skipping the very slow rosdep installation step whenever a source file is changed.
Note that docker-based tests are not run on our macOS Github Action hosts, because they will not install docker on those due to licensing issues.
> Separate rosdep collection from sysroot creation

- ros_cross_compile/docker/build_workspace.sh
This way the script can be verbose, just disable the checks around the sourced `setup.bash` script to suppress its noisiness and unset variables.
> Reenable -ux bash args in build workspace script

- ros_cross_compile/builders.py
- ros_cross_compile/docker/build_workspace.sh
- ros_cross_compile/docker/sysroot.Dockerfile
- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_creator.py
- test/test_builders.py
By removing the arguments and early-set environment variables, we increase docker cache reuse.
The long term goal is to store Docker images on a registry so users can pull rather than recreate common base images.
Removing these arguments and environment variables makes more of the base builder image common. Now the matrix is just [OS, arch].
Another benefit is that the arguments to the `build_workspace` script all must be provided by the caller, which makes everything a bit more explicit.
> Remove arguments from sysroot image

- .github/workflows/test.yml
- README.md
- ros_cross_compile/dependencies.py
- ros_cross_compile/docker/gather_rosdeps.sh
- ros_cross_compile/docker/sysroot.Dockerfile
- ros_cross_compile/docker_client.py
- ros_cross_compile/platform.py
- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_creator.py
- test/run_e2e_test.sh
- test/test_dependencies.py
- test/test_entrypoint.py
- test/test_sysroot_creator.py
Closes #137 
This change removes the requirement for a specific directory structure
* Make the target workspace a required positional argument
* Automatically create a directory, similar to the "sysroot directory" that we previously had users create manually, for the docker build context - it contains the necessary qemu binary, dockerfiles, scripts, and any other extra user inputs
* Update README.dmd to describe the simplified process
> Point the tool at any workspace, don't require specific setup

- ros_cross_compile/docker_client.py
- test/test_docker_client.py
Closes https://github.com/ros-tooling/cross_compile/issues/152
Ensure that `docker run` logs are streamed live as they run. I had earlier used an argument (`run(stream=True)`) that was added in a newer version of docker-py than the one we specify.
We can't remove the container automatically, then, because we have to query its exit code in order to raise an exception on a failure.
> Actually stream docker run output live and add test for it

- ros_cross_compile/mixins/cross-compile.mixin
Remove reconfiguring/cleaning args from build mixin so that incremental builds can happen. A user who wants that level of clean can just remove the preexisting build/install directories before running the build.
Closes #108 
> Enable incremental builds

- test/test_dependencies.py
- test/test_docker_client.py
- test/utilities.py
Some logic was duplicated, so provided this much shorter decorator that can be changed all in one place.
> Create a common decorator for docker-based tests

- .github/workflows/e2e_test.yml
- README.md
- ros_cross_compile/platform.py
- ros_cross_compile/sysroot_creator.py
- test/run_e2e_test.sh
- test/test_platform.py
- test/test_sysroot_creator.py
Closes https://github.com/ros-tooling/cross_compile/issues/118
Enables e2e test for x86 target. Runs considerably faster than the other e2e tests because it is not actually emulated, because our build hosts are x86
> Enabling x86 targets

- README.md
- ros_cross_compile/docker_client.py
- ros_cross_compile/ros_cross_compile.py
- test/dummy_pkg_ros2_py/setup.py
Closes https://github.com/ros-tooling/cross_compile/issues/172
Depends on https://github.com/ros-tooling/cross_compile/pull/171
Allows user to override the name of the colcon defaults file, to be able to pass different list and build arguments for different use cases
> Specify colcon defaults

- tox.ini
On some systems, `/tmp` cannot be mounted properly into Docker container volumes. To avoid this issue entirely, we utilize the virtualenv-specific tmp directory that tox provides.
> Use a temporary directory specific to the virtualenv for tox tests

- ros_cross_compile/dependencies.py
- ros_cross_compile/docker/gather_rosdeps.sh
- ros_cross_compile/ros_cross_compile.py
- test/test_dependencies.py
Fixes #135.
This feature helps user to skip the rosdep keys that are not important for the compilation of package.
Signed-off-by: Snehal Bichkar <snehaldb@amazon.com>
> Allow user to skip rosdep keys.

- .github/workflows/test.yml
Before this commit, one metric was emitted per entry in the workflow
matrix. This is a problem because as it makes our dashboards harder to
read (different repositories have different expected values).
This refactors the workflow to only emit the metric once. If the
workflow fails on either Mac or Windows, 0 is emitted. If it succeeds on
both platforms, 1 is emitted.
This change also forces the worker to run on the Ubuntu Bionic in Docker, to reduce flakiness.
> Refactor workflow to only report metrics once

- .github/workflows/pip_e2e_test.yml
- .github/workflows/test.yml
The nightly workflows should have a different metric name, and the test workflow should use the default name to match the other repositories.
> Fix metric name in workflows

- tox.ini
Schedules / PR builds are failing to run ament_flake8 - e.g. https://github.com/ros-tooling/cross_compile/actions/runs/102916470
ament_flake8 has been fixed on master for flake8 3.8, but we only want to depend on officially released tagged versions.
For now, pin flake8 back to non-breaking version. We can follow up later with an update to ament_lint versions once a fix is available.
> Pin flake8 version until ament_flake8 has a released version that supports the newest

- .github/workflows/test.yml
Move Docker socket mount from `options` into `volumes` since this is where it should belong.
> Mount Docker socket in volumes section

- .github/workflows/e2e_test.yml
- README.md
- ros_cross_compile/docker/sysroot.Dockerfile
- ros_cross_compile/platform.py
- test/run_e2e_test.sh
Closes https://github.com/ros-tooling/cross_compile/issues/184
Depends on https://github.com/ros-tooling/cross_compile/pull/192
The Foxy beta is out, we can now build workspaces against it. However, since it's not officially released, we need to use the `ros2-testing` repo to install dependencies.
Probably won't merge this PR as-is, we should wait until Foxy is out, and the e2e requires no special setup. However, anybody who wants to try it out against the Foxy betas can check out this branch.
> Enable Foxy support

- ros_cross_compile/ros_cross_compile.py
- test/test_entrypoint.py
Allow relative paths for the workspace argument (via `resolve`), and check early if it looks usable, to prevent waiting until later in the process to raise an issue.
Fixes #214 
> Allow relative paths for the workspace argument

- ros_cross_compile/mixins/cross-compile.mixin
With https://github.com/colcon/colcon-mixin/pull/26 colcon-mixin raises an error when asking for a mixin that doesn't exist. Make sure to provide all mixins that are requested in the cross-compile workflows. Reformat to compact YAML for ease of reading and editing while in there.
> Add x86 mixin to fix error, and reformat mixin as compact yaml

- ros_cross_compile/pipeline_stages.py
- test/test_pipeline_stages.py
In an upcoming PR, we will move the current `ros_cross_compile` pipeline to an "abstractified" system that takes advantage of Abstract Base Classes (ABCs). In preparation for that, we add a new customizations tuple, which will streamline this new system.
> Add Customizations Tuple

- ros_cross_compile/data_collector.py
Merged before fixing this from previous PR - make the Units enum contain members naming units of measurement, not measurable properties.
> Fix units to be units instead of measurable properties

- ros_cross_compile/data_collector.py
- test/test_data_collector.py
Meaningful exceptions are provided by code to convey error conditions. The data timer currently suppresses these from being raised and allows the program to silently return a successful return code when a failure happens. Fix that.
> Don't swallow exceptions in the timer

- ros_cross_compile/dependencies.py
- ros_cross_compile/pipeline_stages.py
- test/test_dependencies.py
The pipeline stage abstraction is an ABC, and we implement the dependencies stage in this PR to essentially give an example as to how each pipeline stage class would be implemented.
> Add interface for pipeline stage abstraction and implement dependencies stage

- ros_cross_compile/platform.py
The values are case sensitive, and since we may support different OS values per ROS distribution/architecture, we cannot list this as "choices" in the argparser. Add the supported values to make the situation more clear to the user.
Sample:
```
(venv) 5:40:13 ➜  tiny ros_cross_compile -a aarch64 -o Ubuntu -d foxy .                                                           1s
Traceback (most recent call last):
File "/Users/eknapp/dev/ros/infra/venv/bin/ros_cross_compile", line 11, in <module>
load_entry_point('ros-cross-compile', 'console_scripts', 'ros_cross_compile')()
File "/Users/eknapp/dev/ros/infra/cross_compile/ros_cross_compile/ros_cross_compile.py", line 191, in main
cross_compile_pipeline(args)
File "/Users/eknapp/dev/ros/infra/cross_compile/ros_cross_compile/ros_cross_compile.py" …
```
> Add more informative messaging when user provides unsupported OS value

- ros_cross_compile/data_collector.py
- ros_cross_compile/ros_cross_compile.py
- test/test_data_collector.py
The naming was redundant, "data_" added no useful context
> Rename data_timer api to just "timer"

- ros_cross_compile/builders.py
- ros_cross_compile/sysroot_creator.py
- test/test_builders.py
- test/test_sysroot_creator.py
Add implementations for the sysroot image creation stage and the emulated docker build stage. Also adds tests for the new stages in.
> Implement the remainder of the cross compile stages

- ros_cross_compile/dependencies.py
- ros_cross_compile/pipeline_stages.py
- ros_cross_compile/ros_cross_compile.py
Add the stages implemented in #231 to the pipeline runner implemented in #230 . Also move the name property from each subclass to the parent class (PipelineStage).
> Add the remainder of the stages to the pipeline runner

- ros_cross_compile/docker_client.py
See also: https://docker-py.readthedocs.io/en/stable/change-log.html
(Ctrl+F 'breaking')
> Compatibility with newer versions of docker

- ros_cross_compile/data_collector.py
- ros_cross_compile/ros_cross_compile.py
- test/test_data_collector.py
Specifically allows the user to specify a filename for storing the collected time-series data.
Resolves #210 
> Implement option to add custom filename

- ros_cross_compile/builders.py
- ros_cross_compile/data_collector.py
- ros_cross_compile/dependencies.py
- ros_cross_compile/docker_client.py
- ros_cross_compile/pipeline_stages.py
- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_creator.py
- test/test_builders.py
- test/test_dependencies.py
- test/test_sysroot_creator.py
Some of the stages of the cross compile pipeline make use of a Docker image. For "research" purposes, we want to be able to get the size of these docker images.
Resolves #208 
Resolves #209 
> Implement collection of docker image sizes

- ros_cross_compile/docker_client.py
Use the same internal utility that `DockerClient.from_env()` uses instead of specifying explicit unix path for `docker.sock` for the low level client construction.
Related to https://github.com/ros-tooling/cross_compile/issues/201
> Use kwargs_from_env utility for Docker APIClient creation

- .github/workflows/e2e_test.yml
The if statement that checks if there is a valid metrics json for a given OS/Architecture/ROS Distro combination did not work. This fixes it.
> Change && to || fix if statement logic

- ros_cross_compile/builders.py
- ros_cross_compile/dependencies.py
- ros_cross_compile/pipeline_stages.py
- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_creator.py
- test/test_builders.py
- test/test_dependencies.py
- test/test_pipeline_stages.py
- test/test_sysroot_creator.py
- test/utilities.py
This allows us to remove the "skip-rosdep-collection" really specific option, in favor of a more generic one.
To do this, I needed to define the pipeline stages at a scope where the argument parser can read them. As part of the usability for this, give the stages shorter names. While changing the Options interface, make its naming conventions a little less redundant.
This will increase the iterative development usability and configurability of some upcoming changes, which split out the current CreateSysrootStage into two separate stages, CreateSysroot and CreateBuildEnvironment - as well as a new stage that will come at the end, PackageRuntimeEnvironment
> Generic way to skip pipeline stages

- tox.ini
The latest release of pip3 no longer accepts this URI format. It had been printing warnings for a long time and this last release finally broke.
> Update linter URI for latest pip versions (fixes action CI)

- .github/workflows/test.yml
- ros_cross_compile/sysroot_creator.py
- test/test_builders.py
- tox.ini
The docker-in-docker situation for these pytests did not allow for qemu emulation - those runs failed for this test. So, make the test.yml Ubuntu environment the same as the e2e test.
This doesn't change any existing functionality, it only enables a new test for existing functionality.
> Add and enable a pytest for the emulated build stage

- ros_cross_compile/docker/build_workspace.sh
- test/test_builders.py
Fixes #153
Depends on #276
Use an exit hook in the bash building script to make sure that everything in the workspace is owned by the calling user, rather than by root. Add a test that fails before the change
> chown build outputs even if build fails

- README.md
- ros_cross_compile/docker/build_workspace.sh
- ros_cross_compile/docker/sysroot.Dockerfile
- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_creator.py
- test/test_builders.py
Implements #271
This adds another customizable script hook, this time after the build has completed, allowing the user to postprocess their build outputs in the build environment.
The unit test is for a fairly simple case, the colcon-bundle example in the README has been tested manually but seems overkill for a test.
> Add custom post-build script

- ros_cross_compile/docker/gather_rosdeps.sh
Users should be able to get rosdeps for an EOL distro - the packages are still there.
> Allow users to get rosdeps for eol distro

- ros_cross_compile/docker/sysroot.Dockerfile
Fixes #281 as requested here: https://github.com/ros-tooling/cross_compile/issues/281#issuecomment-751855047
This fix sets DEBIAN_FRONTEND env variable to noninteractive and thus cancels the installations prompts issued by some packages during rosdep-triggered installations.
> cancel installs input prompts

- ros_cross_compile/ros_cross_compile.py
New release caused build to start failing https://pypi.org/project/flake8-blind-except/0.2.0/
I might have pinned back the dependency instead, but it's not a bad catch, so I'd rather just fix the linter complaint
> Remove blind except (caught by flake8-blind-except 0.2)

- .github/workflows/e2e_test.yml
- README.md
- ros_cross_compile/docker/sysroot.Dockerfile
- ros_cross_compile/platform.py
- test/run_e2e_test.sh
- test/test_builders.py
- test/test_platform.py
- test/test_sysroot_creator.py
Following https://discourse.ros.org/t/ros-gpg-key-expiration-incident/20669, this fix has to happen, otherwise the tool is unusable.
> sysroot.Dockerfile: fix GPG keys import given latest ROS GPG Key expiration incident

- .github/workflows/e2e_test.yml
- .github/workflows/pip_e2e_test.yml
- README.md
- ros_cross_compile/platform.py
- ros_cross_compile/sysroot_creator.py
- setup.py
- test/run_e2e_test.sh
- test/test_platform.py
- test/test_sysroot_creator.py
Continues https://github.com/ros-tooling/cross_compile/pull/290.
> Add support for ROS Noetic

- setup.py
Follow-up after https://github.com/ros-tooling/cross_compile/pull/319. Binaries do not have a file extension.
> Add qemu binaries to package_data

- .github/workflows/e2e_test.yml
- .github/workflows/pip_e2e_test.yml
- .github/workflows/test.yml
- README.md
- ros_cross_compile/ros_cross_compile.py
- setup.py
- tox.ini
Python3.5 was deprecated and reached EOL in 2020. The original reason to support this was for Dashing users, which supported 3.5. However, Dashing has also reached EOL. Moving forward we should not bother supporting a deprecated Python version.
`types-pkg_resources` fixes the Python3.6+ builds. Not sure exactly what happened to make this necessary, but it's a simple enough fix.
> Fix mypy by adding types-pkg_resources, and removing Python3.5 support

- README.md
- ros_cross_compile/docker/build_workspace.sh
Just a means to control the build environment. I do not have a strong opinion about how this is achieved (as long as there is a way). As such, I'm open to completely changing this patch if a more suitable alternative exists. 
Thanks for the tool BTW !
> Source /custom-data/setup.bash on sysroot build

- ros_cross_compile/docker/build_workspace.sh
I see it as useful, specially for longer builds where we want to capture the output.
> build_workspace: increase verbosity of the colcon build command

- README.md
The simple example in the [Usage Section](https://github.com/ros-tooling/cross_compile#usage) of the readme no longer succeeds due to rosdep errors (dashing reached its EOL, making it a non-trivial example).
I've changed the targeted rosdistro for the example to `foxy`.
> Replaced EOL dashing with foxy in example

- README.md
- ros_cross_compile/dependencies.py
- ros_cross_compile/docker/build_workspace.sh
- ros_cross_compile/docker/sysroot.Dockerfile
- ros_cross_compile/docker_client.py
- ros_cross_compile/ros_cross_compile.py
- ros_cross_compile/sysroot_creator.py
- test/run_e2e_test.sh
- test/test_dependencies.py
The functionality to set the `defaults.yaml` file to use wasn't functioning as it was marked, and one needed to add `/ros_ws` prefix to the path so we were actually able to get and use the file. In the other hand, this was limiting us to the workspace files we could pass as colcon defaults.
This PR basically now allow us to pass any file to be used as `default.yaml`. The default behavior of setting `defaults.yaml`, even if it was empty, was kept. Also, I removed the enforcement of the event handlers, and the verbs can now be configured through the colcon `defaults.yaml` file that is passed. I added an example of how this can be done to the README.
@emersonknapp looking forward for your review and feedback. This works quite nicely now on my end and I am able to set any config file without …
> Update colcon defaults usage

- .github/workflows/shellcheck.yml
Trying to fix shell checker by switching to the `reviewdog` version of it
Previous version `zbeekman/ShellCheck-Linter-Action@v1.0.1` became deprecated 
Signed-off-by: Michael Orlov <michael.orlov@apex.ai>
> Trying to fix shell checker by switching to the reviewdog version of it

- README.md
We are going to deprecate and archive `cross_compile` repo and rational for that is following:
1. There are no volunteers to support it and I don't have enough knowledge and time to support it as well.
1. We have made a post on Discourse about it in July https://discourse.ros.org/t/call-for-help-maintainership-of-the-ros-cross-compile-tool/26511
1. Community mostly expressed opinion that it's outdated and inefficient. It was recommended to use the native cross-compilation instead of QUEMU
Signed-off-by: Michael Orlov <michael.orlov@apex.ai>
> Add notice about repository deprecation in README.md
