cross_compile/sysroot_compiler.py
test/test_flake8.py
test/test_sysroot_compiler.py

Original Author: Prajakta Gokhale <prajaktg@amazon.com>

Fix flake8 issues

---

README.md
cross_compile/ros2_cross_compile.py

Addresses #36.
* Update README with better install instructions 
* Tell users that sysroot path needs to be absolute

Documentation Fixes

---

README.md

Fixes https://github.com/ros-tooling/cross_compile/issues/48.

Document supported Python versions

---

.github/workflows/test.yml

Update workflow to run on MacOS-latest

---

README.md

- remove weasel words
- drop mentions of Ubuntu platform we do not want to support
- remove passive sentences

Improve README.md wording

---

README.md
cross_compile/Dockerfile_ros2
cross_compile/ros2_cross_compile.py
cross_compile/sysroot_compiler.py
test/test_sysroot_compiler.py

Allow user to provide custom setup script

---

test/run_e2e_test.sh

Fix shellcheck warnings in e2e test

---

README.md

Closes #68
Followed through the steps step-by-step and verified that it works. This is the same process that is followed by the e2e tests, the only difference being path names.

Write usage tutorial in README

---

README.md
cross_compile/ros2_cross_compile.py
cross_compile/sysroot_compiler.py
test/test_sysroot_compiler.py

* Add README section documenting supported targets
* Centralize supported targets into one place and add note to update README
Fixes #99 

Document supported target platforms

---

ros_cross_compile/ros_cross_compile.py
ros_cross_compile/sysroot_compiler.py
test/run_e2e_test.sh
test/test_sysroot_compiler.py

This argument's presence is misleading since it is never used.

Remove rmw option which was never connected to anything

---

README.md

It took me some minutes to figure out why rosdep would not resolve my melodic dependencies :)

Add --rosdistro option to description

---

README.md

Fixes https://github.com/ros-tooling/cross_compile/issues/144

Fix bugs in README.md

---

.github/workflows/shellcheck.yml
ros_cross_compile/docker/build_workspace.sh

Add shellcheck workflow to lint shell scripts

---

docs/source/conf.py
docs/sphinx_build_symlink/setup.py
ros_cross_compile/builders.py
ros_cross_compile/docker_client.py
ros_cross_compile/sysroot_creator.py
test/test_mypy.py
test/test_sysroot_creator.py
tox.ini

Add mypy linter and fix issues it raised

---

DEVELOPING.md

Add document with some basic development notes and guidelines for design decisions.

Add DEVELOPING.md 

---

ros_cross_compile/docker/sysroot.Dockerfile

This clean and update is not needed.

Remove line that takes time and provides no benefit

---

ros_cross_compile/dependencies.py
ros_cross_compile/ros_cross_compile.py
test/test_entrypoint.py

Resolves #140 
Implemented a cross compile feature that allow user to skip ros dependencies.

Allow user to skip rosdep collection

---

ros_cross_compile/dependencies.py
ros_cross_compile/ros_cross_compile.py
tox.ini

Depends on https://github.com/ros-tooling/cross_compile/pull/192

Fix missing spaces between words in multiline strings and clean up wording a little

---

.github/workflows/test.yml

Add documentation to test workflow for Docker fix

---

ros_cross_compile/docker/gather_rosdeps.sh
test/test_dependencies.py

Fixes https://github.com/ros-tooling/cross_compile/issues/165
See the issue for the rationale behind making this change

Squash all apt installation commands into a single command

---

ros_cross_compile/data_collector.py
ros_cross_compile/ros_cross_compile.py
ros_cross_compile/sysroot_creator.py
test/test_data_collector.py

Time the cross compile pipeline from end to end

---

ros_cross_compile/dependencies.py
ros_cross_compile/ros_cross_compile.py
test/test_entrypoint.py

We slowly introduce the streamlined pipeline running in `ros_cross_compile.py`. As more of the stage wrappers are introduced, more stages will be added to the pipeline running.

Introduce pipeline runner framework, using the DependenciesStage

---

test/run_e2e_test.sh
test/test_data_collector.py

Verifies that within the entire pipeline, the file creation is successful.

Add case to end-to-end test script to validate creation of file tracking collected metrics

---

.github/workflows/e2e_test.yml

Add namespace specification to second publishing call

---

.github/workflows/e2e_test.yml
.github/workflows/pip_e2e_test.yml
.github/workflows/test.yml

Signed-off-by: Devin Bonnie <dbbonnie@amazon.com>

Ignore reporting metrics from forks

---

README.md
ros_cross_compile/docker/runtime.Dockerfile
ros_cross_compile/pipeline_stages.py
ros_cross_compile/ros_cross_compile.py
ros_cross_compile/runtime.py
test/run_e2e_test.sh
test/test_pipeline_stages.py
test/utilities.py

Allow user to optionally package up a docker image containing the resulting build

Runtime image packaging feature

---

setup.py

Getting ready to release latest features

Bump version to 0.6.0

---

.github/workflows/e2e_test.yml
README.md
ros_cross_compile/platform.py
test/run_e2e_test.sh

Add ROS 2 Rolling support

---

README.md

Closes #291
Decided to use a single package from `demos`, as it is maintained by OSRF.
Ran through the tutorial locally, copy-pasting all commands, and got the described results.

Update tutorial to use demo_nodes_cpp on Foxy, instead of now-deleted file_talker on Dashing

---

README.md

Suggested in https://github.com/ros-tooling/cross_compile/issues/313#issuecomment-848109284

Add Troubleshooting with gitlab example

---

.github/workflows/e2e_test.yml
.github/workflows/test.yml
README.md
ros_cross_compile/platform.py
test/run_e2e_test.sh

This pull request adds support for using this tool with ROS2 Galactic.

Add support to ROS2 Galactic

---

.github/workflows/e2e_test.yml
.github/workflows/pip_e2e_test.yml
.github/workflows/test.yml
.readthedocs.yml
DEVELOPING.md
README.md
ros_cross_compile/dependencies.py
ros_cross_compile/docker/rosdep_focal.Dockerfile
ros_cross_compile/platform.py
ros_cross_compile/ros_cross_compile.py
setup.py
test/run_e2e_test.sh
test/test_dependencies.py
test/test_entrypoint.py
test/test_platform.py
test/test_sysroot_creator.py

- Duplicate #369 with updates in e2e tests.
Update platform.py and README.md to follow the updated REP-2000 - delete dashing add humble update rolling
Solve this issue
https://github.com/ros-tooling/cross_compile/issues/368#issue-1464483861
Note: I cherry picked original commit and add fixes for e2e tests since original fork doesn't allow to push commits from repo maintainers.

Updates to follow the updated rep 2000

---

ros_cross_compile/docker/rosdep.Dockerfile
ros_cross_compile/docker/sysroot.Dockerfile
ros_cross_compile/docker_client.py

This fixes the bug that I had: https://github.com/ros-tooling/cross_compile/issues/360
Not sure if anyone else is having this issue, so if not feel free to ignore!

Quick fix for issue #360

---

ros_cross_compile/docker/rosdep_focal.Dockerfile

- Closes #360 
- Follow up for #361
- Propagate missing changes after rebase
Signed-off-by: Michael Orlov <michael.orlov@apex.ai>

Replace gnupg2 and dirmngr in rosdep_focal.Dockerfile
